export class ArchDecisionDomainError extends Error {}

export class ArchDecisionDomainConditionVerificationError extends ArchDecisionDomainError {}

export class DecisionDoesNotContainThisOptionsError extends ArchDecisionDomainConditionVerificationError {}
export class DecisionDoesNotContainThisCriteriaError extends ArchDecisionDomainConditionVerificationError {}
export class GuestNotInvitedForThisDecisionError extends ArchDecisionDomainConditionVerificationError {}
export class VoteAlreadyComputedError extends ArchDecisionDomainConditionVerificationError {}

export class ArchDecisionVotingIsntFinishedError extends ArchDecisionDomainConditionVerificationError {}

export class ArchDecisionRepeatedParameterError extends ArchDecisionDomainConditionVerificationError {};
export class ArchDecisionMoreThanOneCreatorGuestError extends ArchDecisionDomainConditionVerificationError {};
